#!/bin/bash

source "$CONFIG_DIR/settings/colors.sh"
source "$CONFIG_DIR/settings/icons.sh"
source "$CONFIG_DIR/settings/constant.sh"
source "$CONFIG_DIR/settings/icon_map.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

# Setting up the general bar appearance of the bar
bar=(
	height=36
	notch_display_height=36
	notch_offset=0
	shadow=off
	position=bottom
	sticky=on
	padding_right=4
	padding_left=4
	margin=9
	corner_radius=$BAR_CORNER_RADIUS
	topmost=window
	blur_radius=0
	y_offset=1
	color=$BAR_COLOR
	border_color=$BORDER_COLOR
	border_width=1
)

sketchybar_bottom --bar "${bar[@]}"

# Setting up default item properties
defaults=(
	updates=when_shown

	# padding
	padding_right=5
	padding_left=5

	# icon
	icon.drawing=on
	icon.font="$FONT:Regular:14.0"
	icon.color=$ICON_COLOR
	icon.padding_left=6
	icon.padding_right=4
	#
	# # label/text
	label.font="$FONT:Regular:14.0"
	label.color=$LABEL_COLOR
	label.padding_left=4
	label.padding_right=6

	# background
	background.height=25
	background.border_width=1
	background.padding_left=3
	background.padding_right=3
	background.corner_radius=$ITEM_CORNER_RADIUS

	# popup
	popup.blur_radius=20
	popup.background.border_width=2
	popup.background.corner_radius=$ITEM_CORNER_RADIUS
	popup.background.shadow.drawing=on

	scroll_texts=on
)

sketchybar_bottom --default "${defaults[@]}"

# left items
source "$ITEM_DIR/space.sh"

# center items
source "$ITEM_DIR/music.sh"

# right items
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/package_manager.sh"

# sketchybar_bottom --hotload on

sketchybar_bottom --update

echo "sketchybar_bottom configuation loaded.."
