
# tap repositories and their packages

tap homebrew/core
brew atac
brew atuin
brew bash
brew bat
brew brotli
brew btop
brew c-ares
brew ca-certificates
brew cava
brew certifi
brew dust
brew eza
brew fastfetch
brew fd
brew fftw
brew fnm
brew fzf
brew gcc
brew gettext
brew gh
brew git
brew git-delta
brew gmp
brew go
brew grep
brew helix
brew hwloc
brew icu4c@77
brew ifstat
brew iniparser
brew isl
brew jq
brew lazydocker
brew lazygit
brew libevent
brew libgit2
brew libidn2
brew libmpc
brew libnghttp2
brew libssh2
brew libunistring
brew libuv
brew lld@19
brew llvm@19
brew lpeg
brew lua
brew luajit
brew luv
brew lz4
brew mas
brew mpdecimal
brew mpfr
brew ncurses
brew neovim
brew node
brew nowplaying-cli
brew oh-my-posh
brew oniguruma
brew open-mpi
brew openssl@3
brew pcre2
brew pipes-sh
brew pkgconf
brew pmix
brew portaudio
brew readline
brew ripgrep
brew spicetify-cli
brew sqlite
brew superfile
brew switchaudio-osx
brew television
brew terminal-notifier
brew tlrc
brew tmux
brew tree-sitter
brew tty-clock
brew unibilium
brew utf8proc
brew web-ext
brew wget
brew xz
brew zig
brew zoxide
brew zsh-autosuggestions
brew zsh-syntax-highlighting
brew zstd

tap homebrew/cask
cask alt-tab
cask bitwarden
cask bruno
cask font-hack-nerd-font
cask font-jetbrains-mono-nerd-font
cask font-meslo-lg-nerd-font
cask font-monaspace-nerd-font
cask font-space-mono-nerd-font
cask font-zed-mono-nerd-font
cask pearcleaner
cask powershell
cask sf-symbols
cask wezterm

tap homebrew/services

tap blackmann/brew

tap felixkratz/formulae
brew borders
brew sketchybar

tap jandedobbeleer/oh-my-posh

tap jesseduffield/lazydocker

tap jesseduffield/lazygit

tap jesseduffield/lazynpm
brew lazynpm

tap julien-cpsn/atac

tap nikitabobko/tap
cask aerospace

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1444383602 Goodnotes (6.6.49)
appstore 497799835 Xcode (16.4)
