#!/usr/bin/env bash

bg_color="#1f1f26"
fg_color="#c5c9c7"

windows_bg_color="#393B44"
windows_fg_color="#A4A7A4"

tmux set -g status-style fg=${fg_color},bg=${bg_color}
tmux set -g message-style fg=${fg_color},bg=${bg_color}

tmux set-window-option -g window-status-current-style bg=${windows_bg_color},fg=${windows_fg_color}
tmux set-window-option -g window-status-style bg=${bg_color},fg=${windows_fg_color}
tmux set -g window-status-separator " "

tmux set -g window-status-current-format "#[fg=#c8c093,bg=#393836]#[bg=#c8c093,fg=#393836] #I #W  #[fg=#c8c093,bg=#393836]"
tmux set -g window-status-format "#[bg=#1f1f26,fg=#393836]#[fg=#c8c093,bg=#393836] #I:#W #[bg=#1f1f26,fg=#393836]"

tmux set -g status-left ' #{?client_prefix,#[fg=#c8c093]⧗ ,#S} #(cat #{socket_path}-\#{session_id}-vimbridge)' 
tmux set -g status-right '#(cat #{socket_path}-\#{session_id}-vimbridge-R) #[bg=#1f1f26,fg=#c5c9c7] #(~/.config/tmux/cwd.sh) '

tmux set -g focus-events on
tmux set -g status-left-length 99
tmux set -g status-right-length 99
tmux set -g status-justify absolute-centre

